site_name: FISI Lernfeld 4

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_FISI_LF04/

site_url: https://herr-nm.github.io/MMBbS_FISI_LF04/

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Kapitel 00 - Organisatorisches: '00_organisatorisches.md'
    - Kapitel 01 - Vorstellung der Modellunternehmen: '01_modellunternehmen.md'
    - Kapitel 02 - Schutzziele der Informationssicherheit sicherstellen: '02_schutzziele.md'
    - Kapitel 03 - Schutzbedarfsanalyse planen: '03_schutzbedarfsanalyse_planen.md'
    - Kapitel 04 - Bedrohungen und Schadenszenarien einordnen: '04_bedrohungen_szenarien.md'
    - Kapitel 05 - Schutzbedarfsanalyse durchführen und bewerten: '05_schutzbedarfsanalyse_durchfuehren.md'